#!/usr/bin/env perl

use Mojolicious::Lite;
use Email::MIME;
use IO::All;
use Email::Sender::Simple qw(sendmail);
use Email::Sender::Transport::SMTP ();
#use Email::Simple ();
#use Email::Simple::Creator ();

post '/betasignup' => sub {
    my $self = shift;
    
    my $jsonReq = $self->req->json;
    my $email = $jsonReq->{email};
    #my $email = $self->param('email');

    open(EMAILS, '>>', 'emails.txt');
    print EMAILS $email . "\n";
    close EMAILS;
    
    my $base64Img = "";

    my @parts = (
        Email::MIME->create(
            attributes => {
                content_type => "text/html"
            },
            body => "<table><tr><td><img src=\"http://annotree.com/Email/HeaderLeft.png\" border=\"0\" alt=\"\" /><img style=\"float:right\" src=\"http://annotree.com/Email/HeaderRight.png\" border=\"0\" alt=\"AnnoTree\" /></td></tr><tr><td style=\"color:#000000\">Thanks for signing up to use the AnnoTree beta. We will let you know when you can join the AnnoTree beta and get started.<br/><br/>Sincerely,<br/>The AnnoTree Team</td></tr></table>"
        )
    );

    my $smtpserver = 'smtp.mailgun.org';
    my $smtpport = 587;
    my $smtpuser   = 'postmaster@annotree.com';
    my $smtppassword = '8-7sigqno8u7';

    my $transport = Email::Sender::Transport::SMTP->new({
      host          => $smtpserver,
      port          => $smtpport,
      sasl_username => $smtpuser,
      sasl_password => $smtppassword
    });

    my $emailObj = Email::MIME->create(
      header => [
        To              => $email,
        From            => '"AnnoTree" <invite@annotree.com>',
        Subject         => 'Thanks for Signing Up for AnnoTree',
        content_type    => 'multipart/mixed'
      ],
      parts => [@parts]
    );

    sendmail($emailObj, { transport => $transport }); 
    
    $self->render(status => 204, text => 'Success');
};

app->start;
